version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5

  pgServer:
    container_name: pgServer
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  client:
    container_name: pgAdmin
    image: dpage/pgadmin4
    depends_on:
      - pgServer
    environment:
      - PGADMIN_DEFAULT_EMAIL=mo7amed7assan1911@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"